apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-telemetry-api
  namespace: f1-telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f1-telemetry-api
  template:
    metadata:
      labels:
        app: f1-telemetry-api
    spec:
      containers:
      - name: api
        image: ghcr.io/phish3y/f1-telemetry-api:49b332f995360cb6fe1d5c71c362cdec11a24fd3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: RUST_LOG
          value: "debug"
        - name: API_URL
          value: "0.0.0.0"
        - name: API_PORT
          value: "3000"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "10.100.80.208:9094"
        - name: SPEED_AGGREGATION_TOPIC
          value: "speed-aggregation"
        - name: RPM_AGGREGATION_TOPIC
          value: "rpm-aggregation"
---
apiVersion: v1
kind: Service
metadata:
  name: f1-telemetry-api
  namespace: f1-telemetry
spec:
  type: ClusterIP
  selector:
    app: f1-telemetry-api
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
