---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: f1-telemetry
  namespace: f1-telemetry
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  rules:
  - host: f1.phish3y.cc
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: f1-telemetry-api
            port:
              number: 3000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: f1-telemetry-web
            port:
              number: 3000
  tls:
  - hosts:
    - f1.phish3y.cc
    secretName: letsencrypt
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger
  namespace: f1-telemetry
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  rules:
  - host: jaeger.phish3y.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jaeger
            port:
              number: 16686
  tls:
  - hosts:
    - jaeger.phish3y.cc
    secretName: jaeger-tls
